### PR TITLE
#1945 Fixed multiselect infinite loop after after Carbon v11.57.0 update

### LINKED ISSUE #1945: Fix multiselect infinite loop issue after after Carbon v11.57.0 update
Ref: 3789

Elyra builds are failing since 5/9/2024 after Carbon released new version 11.57.0.

In latest carbon version [v11.57.0](https://github.com/carbon-design-system/carbon/releases/tag/v11.57.0), seeing this error for Multiselect control -
```
Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.
```

Because of this our unit tests are failing due to infinite loop.

Carbon team suggested this solution -
It looks like you could update your `handleOnChange` to compare the `selectedItems` that are in the event with your existing list, and only update the value if they have changed. This would include refactoring to not call  `genSelectOptions` on every render and to used a stored value instead.

### PR DESCRIPTION
**Pull request by nmgokhale**
Fixes #1945 

Initializing `multiSelectDropdown` in render() was causing the infinite loop.
To fix the issue, created a class variable `this.multiSelectDropdown` in constructor and only update its value when either `selectedOptions` have changed or `controlOpts` have changed in case of filterable Multiselect. 

 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

File: canvas_modules/common-canvas/src/common-properties/controls/multiselect/multiselect.jsx [hunk 1]
```diff
@@ -112,11 +118,15 @@ class MultiSelectControl extends React.Component {
 		for (let i = 0; i < evt?.selectedItems?.length; i++) {
 			controlValues.push(evt.selectedItems[i].id);
 		}
+		if (!isEqual(this.selectedOptions, controlValues)) {
```
Comment (matthoward366) [inline canvas_modules/common-canvas/src/common-properties/controls/multiselect/multiselect.jsx:121]: Is this check actually needed?  Wouldn't the `handleOnChange` method only be called if values change?

Comment (nmgokhale) [reply canvas_modules/common-canvas/src/common-properties/controls/multiselect/multiselect.jsx:121]: Carbon team also suggested to add this check -

> It looks like you could update your handleOnChange to compare the selectedItems that are in the event with your existing list, and only update the value if they have changed.

Removing this check causes infinite loop again. 

Infinite loop happens because -

1. We update `this.multiSelectDropdown = this.genSelectOptions(controlValues);` in `handleOnChange()`
2. We call `this.props.controller.updatePropertyValue()` in `handleOnChange()`
3. After the `updatePropertyValue` is complete, `componentDidUpdate()` is called in which we update `this.multiSelectDropdown = this.genSelectOptions(controlValues);` again
4. Because `this.multiSelectDropdown` is updated, again `handleOnChange()` method is called and Steps 1-4 keep happening in loop

Comment (matthoward366) [reply canvas_modules/common-canvas/src/common-properties/controls/multiselect/multiselect.jsx:121]: I see.  Thanks for the explanation.
