### PR TITLE
#1440 Accessibility: Fixed 'aria-labelledby' are not valid for the element <div> with implicit ARIA role 'generic'

### LINKED ISSUE #1440: Accessibility: The ARIA attributes "aria-labelledby" are not valid for the element <div> with implicit ARIA role "generic"
Ref: 3516

This type of violation is seen in Toolbar -
toolbar

And properties table headers -
properties-table-headers

### PR DESCRIPTION
**Pull request by nmgokhale**
Fixes #1440 

Before - 
before

After - 
after

 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

File: canvas_modules/common-canvas/src/tooltip/tooltip.jsx [hunk 1]
```diff
@@ -362,7 +362,7 @@ class ToolTip extends React.Component {
 				onBlur={this.props.showToolTipOnClick ? onBlur : null}
 				tabIndex={this.props.showToolTipOnClick ? 0 : null}
 				role={this.props.showToolTipOnClick ? "button" : null}
-				aria-labelledby={`${this.uuid}-${this.props.id}`}
+				aria-labelledby={this.props.showToolTipOnClick ? `${this.uuid}-${this.props.id}` : null}
```
Comment (nmgokhale) [inline canvas_modules/common-canvas/src/tooltip/tooltip.jsx:365]: Add `Aria-labelledby` attribute only when `role="button"`

**Review by caritaou — APPROVED** [review]
