### PR TITLE
#1531 Fixed custom conditions shows repeated error message

### LINKED ISSUE #1531: Custom conditions show repetitive error message
Ref: 3578

For custom conditions operating on table cell, validation message is added on table and each cell. This results in repetitive error messages.

https://github.com/elyra-ai/canvas/assets/25124000/913c9aa7-9f6c-419b-8e8a-ed8e02ff83ab

### PR DESCRIPTION
**Pull request by nmgokhale**
Fixes #1531 

For common-properties internal conditions, error message is set in the correct format -
Screenshot 2023-07-20 at 2 51 38 PM

For custom conditions, error message format is incorrect -
Screenshot 2023-07-20 at 2 52 52 PM

Added code for - table level error should be cleared before adding a cell-level error.

 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

File: canvas_modules/common-canvas/src/common-properties/ui-conditions/conditions-utils.js [hunk 1]
```diff
@@ -709,6 +709,15 @@ function _validateInput(propertyId, controller, control, showErrors) {
 				if (!controller.getErrorMessage(msgPropertyId, true, true, false)) {
 					errorSet = false;
 				}
+				// Before setting an error message for table cell, clear the error message for table (if any)
+				if (typeof msgPropertyId.row !== "undefined" || typeof msgPropertyId.col !== "undefined") {
+					const tablePropertyId = controller.convertPropertyId(msgPropertyId.name);
+					const tableErrorMessage = controller.getErrorMessage(tablePropertyId);
+					if (tableErrorMessage !== null) {
+						controller.updateErrorMessage(tablePropertyId, null);
```
Comment (caritaou) [inline canvas_modules/common-canvas/src/common-properties/ui-conditions/conditions-utils.js:717]: What is the behavior is you use clearErrorMessages instead of update?

**Review by caritaou — COMMENTED** [review]
The behavior of this is odd. Unchecking the checkbox should've cleared all the errors but I still see them
condition
conditions2

File: canvas_modules/common-canvas/src/common-properties/ui-conditions/conditions-utils.js [hunk 2]
```diff
@@ -709,6 +709,15 @@ function _validateInput(propertyId, controller, control, showErrors) {
 				if (!controller.getErrorMessage(msgPropertyId, true, true, false)) {
 					errorSet = false;
 				}
+				// Before setting an error message for table cell, clear the error message for table (if any)
+				if (typeof msgPropertyId.row !== "undefined" || typeof msgPropertyId.col !== "undefined") {
```
Comment (matthoward366) [inline canvas_modules/common-canvas/src/common-properties/ui-conditions/conditions-utils.js:713]: Is this still needed?

Comment (nmgokhale) [reply canvas_modules/common-canvas/src/common-properties/ui-conditions/conditions-utils.js:713]: Yes. This code is fixing the following repeated error messages issue - 
Screenshot 2023-07-27 at 10 52 40 AM

**Review by matthoward366 — APPROVED** [review]
