### PR TITLE
#1375 Fix glmm example in properties

### LINKED ISSUE #1375: glmm example is broken in test harness
ref 3481

image

### PR DESCRIPTION
**Pull request by caritaou**
fixes #1375 
 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

File: canvas_modules/harness/src/client/components/ctrl/CustomEffectsCtrl.jsx [hunk 1]
```diff
@@ -76,6 +76,8 @@ class CustomEffectsCtrl extends React.Component {
 	}
 
 	componentDidMount() {
+		this.controller.setAddRemoveRows(this.SOURCE_LIST_ID, false);
```
Comment (matthoward366) [inline canvas_modules/harness/src/client/components/ctrl/CustomEffectsCtrl.jsx:79]: Why do we need to add this?

Comment (caritaou) [reply canvas_modules/harness/src/client/components/ctrl/CustomEffectsCtrl.jsx:79]: This is added to remove the buttons from the table, to align our examples.
The `add_remove_rows` uihint did not take affect because this control is being created directly through controlFactory. We call `this.setInitialAddRemoveRows()` when setting the form. This is one way to ensure the buttons are hidden for the controls created

**Review by matthoward366 — APPROVED** [review]
lgtm
