### PR TITLE
#1468 Datepicker controls are in the wrong color within a Tearsheet

### LINKED ISSUE #1468: Datepicker and DatepickerRange are in the wrong color within a Tearsheet
ref 3537

image

### PR DESCRIPTION
**Pull request by caritaou**
fixes #1468 
 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

File: canvas_modules/harness/src/client/components/sidepanel/properties/sidepanel-properties.jsx [hunk 1]
```diff
@@ -177,7 +177,6 @@ export default class SidePanelProperties extends React.Component {
 		} else {
 			this.getSelectedFile();
 		}
-		this.props.propertiesConfig.closeSidePanelModal();
```
Comment (caritaou) [inline canvas_modules/harness/src/client/components/sidepanel/properties/sidepanel-properties.jsx:180]: I forgot to change this last time when updating the test harness

**Review by nmgokhale — APPROVED** [review]
