### PR TITLE
#1981 Fixed unable to see tooltip for table headers having checkbox

### LINKED ISSUE #1981: Unable to see tooltip for table headers having checkbox
Ref: 3755

After opening `Conditions_paramDef.json` and trying to click on `More Tables` > `Configure Dummy Types`, when I hover on `Override` column tooltip is not showing up.

https://github.com/elyra-ai/canvas/assets/25124000/ddd50bba-8712-4471-bda7-4e5709ffb702

Enable 1 cypress test in `properties-tooltips.cy.js` after this bug is fixed

### PR DESCRIPTION
**Pull request by nmgokhale**
Fixes #1981 
 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

File: canvas_modules/common-canvas/src/common-properties/components/truncated-content-tooltip/truncated-content-tooltip.jsx [hunk 1]
```diff
@@ -30,7 +30,7 @@ export default class TruncatedContentTooltip extends React.Component {
 			tooltipText = String(this.props.tooltipText);
 		}
 		if (this.props.content && this.props.content.type === Checkbox && this.tooltipRef && this.tooltipRef.firstChild) {
-			truncatedRef = this.tooltipRef.firstChild.lastChild; // checkbox label is in div -> label -> span
+			truncatedRef = this.tooltipRef.firstChild.lastChild.previousSibling; // checkbox label is in div -> label -> span
```
Comment (nmgokhale) [inline canvas_modules/common-canvas/src/common-properties/components/truncated-content-tooltip/truncated-content-tooltip.jsx:33]: `this.tooltipRef.firstChild.lastChild` was returning `<div class="cds--checkbox__validation-msg"></div>`

`this.tooltipRef.firstChild.lastChild.previousSibling` returns checkbox label `<label />`

**Review by caritaou — APPROVED** [review]
