### PR TITLE
#1097 Fixed page freeze for multiple row tables having subpanels

### LINKED ISSUE #1097: Page freezes for multiple row tables having subpanels
Environment
mac with Chrome or Firefox. The key is scrollbars need to be on.

Recreate
- Open paramDef in test harness. Make sure to have scrollbars on or external mouse plugged in
- Scroll and try to open/change settings in the type table
- Currently the browser freezes. Without the scrollbars enabled everything works fine.

[type_node.json.zip](https://github.com/elyra-ai/canvas/files/9031911/type_node.json.zip)

When a table has 5+ rows and every row has a subpanel cell, page freezes when hovered over "edit" icon. 
Screen Shot 2022-07-01 at 3 29 41 PM

### PR DESCRIPTION
**Pull request by nmgokhale**
Fixes #1097 

 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

File: canvas_modules/common-canvas/src/tooltip/tooltip.jsx [hunk 1]
```diff
@@ -177,7 +177,7 @@ class ToolTip extends React.Component {
 				}
 			} else if (tooltipDirection === "left") {
 				// For long tooltips, tooltip.offsetWidth is updated after setting tooltip.style.left. Ensure tooltip doesn't overlap tooltipTrigger element.
-				while ((tooltip.offsetLeft + tooltip.offsetWidth + pointerLayout.width) > triggerLayout.left) {
+				while ((tooltip.offsetLeft + tooltip.offsetWidth + pointerLayout.width) > Math.round(triggerLayout.left)) {
```
Comment (nmgokhale) [inline canvas_modules/common-canvas/src/tooltip/tooltip.jsx:180]: `tooltip.offsetLeft` is a whole number. So rounding off `triggerLayout.left` to get rid of decimal part which was causing the infinite loop.

**Review by matthoward366 — APPROVED** [review]
Nice find.  Changes look good.
